// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqtkvsmarqxcquewxfyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxdGt2c21hcnF4Y3F1ZXd4Znl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTEzNzEsImV4cCI6MjA2OTY4NzM3MX0.aKc6XAPI3AccdqPYJ6I5Ln-vH7Fl20kV_u89ogaBaM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});